### PR TITLE
Fixing breadcrumbs 404 & Unique key prop warning on resource sidebar

### LINKED ISSUE #198: Handle sub-directory pages
Sub-directories.... either we generate pages for them (via gatsby-node), or we stop linking to them all-together in the breadcrumbs. Maybe there isn't a huge benefit to sub-directories, so probably just not linking to them would make more sense...

### PR DESCRIPTION
**Pull request by puremana**
closes #198

Folders in resources that aren't the root folder have content.
[https://gyazo.com/2b0a2cee0c6b4ba586ad6384d85c010b](https://gyazo.com/2b0a2cee0c6b4ba586ad6384d85c010b)

To fix this I don't link the second or more folder when rendering the breadcrumbs (not the best solution but since we can't tell if an item's path exists it's the best I could come up with)

This is what it looks like after the fix

image

I also noticed that there was this error relating to unique key props in the resource sidebar

image

and have fixed it accordingly.

Thanks

### CODE REVIEW

File: src/components/Breadcrumb/index.tsx [hunk 1]
```diff
@@ -32,7 +32,7 @@ function flatten([
 export function Breadcrumb({ relativePath, basePath }: IBreadcrumbProps) {
   const paths = relativePath.split("/")
   const breadcrumbItems = flatten([traversePaths(paths, basePath)])
-
+  let count = 0;
```
Comment (veksen) [inline src/components/Breadcrumb/index.tsx]: perhaps a better name, like `foldersDepth` would be better?

**Comment by veksen** [comment]
sorry for the delay! crazy week, left a comment

File: src/components/Breadcrumb/index.tsx (hunk 1 above)
Comment (puremana) [reply src/components/Breadcrumb/index.tsx]: Yeah definitely, bad habit of mine
